spring:
  application:
    name: @project.name@
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jackson:
    default-property-inclusion: non_absent

server:
  error:
    include-stacktrace: never