name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build api doc"
    strategy:
      matrix:
        java: [ 11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: >
            [
              {
                "id": "springframework-repository",
                "name": "springframework-repository",
                "url": "https://maven.springframework.org/milestone"
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "repository.spring.release",
                "name": "spring.milestone",
                "url": "https://repo.spring.io/plugins-release"
              }
            ]
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw -B help:effective-settings


      - name: GitHub Pages action
        if: |
          github.ref == 'refs/heads/master' &&
           matrix.java == 11
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/generated-docs